config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'adoptees#new'
  get  '/adoptees', to: 'adoptees#index' 
 resources :adoptees
 end

app/models/adoptee.rb
class Adoptee < ApplicationRecord

before_save { email.downcase! } 

before_save { name.downcase! }

validates :name,  presence: true, length: { maximum: 50 }

VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

validates :email, presence: true, length: { maximum: 255 }, format: {with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }

validates :personality, presence: true, length: { maximum: 500}

validates :age, presence: true

has_secure_password

validates :password, presence: true, length: { minimum: 6 }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/adoptees_controller.rb
class AdopteesController < ApplicationController

# before_action :logged_in_user, only: [:index, :edit, :update]

def index
@adoptees = Adoptee.all  
 end

def show
    @adoptee = Adoptee.find(params[:id])
#debugger 
 end
  
def new
@adoptee = Adoptee.new
end

def create
    @adoptee = Adoptee.new(adoptee_params)
    if @adoptee.save
          flash[:success] = "You are soon on your way to being adopted!" 
 redirect_to @adoptee
    else
      render 'new'
    end
  end

def adoptee_params
      params.require(:adoptee).permit(:name, :age, :email, :personality,  :password,
                                   :password_confirmation)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	 names = %w[Steffie Linh Anya Liam]
	 @result = names.shuffle.first
  end

  def help
  end
  
  def about
  end
 
  def contact
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

# before_action :logged_in_user, only: [:index, :edit, :update]

def index
  @users = Adoptee.all 
 end

def show
    @adoptee = Adoptee.find(params[:id])
#debugger 
 end
  
#def new
 # end
end

app/helpers/adoptees_helper.rb
module AdopteesHelper

 # Returns the Gravatar for the given adoptee.
  def gravatar_for(adoptee, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(adoptee.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: adoptee.name, class: "gravatar")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Adopt A CS Major"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

 # Returns the Gravatar for the given adoptee.
  def gravatar_for(adoptee, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(adoptee.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: adoptee.name, class: "gravatar")
  end

end

app/views/adoptees/index.html.erb
<% provide(:title, 'Adoptees') %>
<h1>All Adoptees</h1>



<ul class="users"> 
 <% @adoptees.each do |adoptee| %>
    <li>
      <%= gravatar_for adoptee, size: 50 %>
      <%= link_to adoptee.name, adoptee %>
    </li>
  <% end %>
</ul>

app/views/adoptees/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@adoptee) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :age %>
      <%= f.number_field :age, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :personality %>
      <%= f.text_field :personality, class: 'form-control' %>     
      
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/adoptees/show.html.erb
<% provide(:title, @adoptee.name) %>
<div class = "row">
<aside class = "col-md-4">
<section class = "user_info">

<%= gravatar_for @adoptee %>
<br>
<h1 style="font-size: 23 px;">
<%= @adoptee.name %>
</h1>
<br>
<br>
<h1 style="font-size: 16px;">
Age: <%= @adoptee.age %>
</h1>
<br>
<h1 style="font-size: 16 px;">
Email: <%=  @adoptee.email %>
</h1>
<br>
<h1 style="font-size: 16 px;">
Personality: <br> <%= @adoptee.personality %>
</h1>

</section>
</aside>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Website created by Stefanie Ochoa </small>
 <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://www.cs.grinnell.edu/" target="_blank">Grinnell CS</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Adopt A CS Major", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "Help",    help_path %></li>
        <li><%= link_to "Adoptees", adoptees_path %></li>
	
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>   
 </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @adoptee.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@adoptee.errors.count, "error") %>.
    </div>
    <ul>
    <% @adoptee.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<h2>The Website</h2>
<p>
This is a site meant for non computer science majors, professors, and additional people to find a lonely computer science major student at Grinnell College, IA to contact and figuratively "adopt". This site is meant to help people become connected and create meaningful relationships. If you're interesting in "adopting" just look through our list of adoptees on the 'Adoptees' tab in the navigation bar!
</p>
<h2>My Skill Development </h2>
<p>	Hey there! <br>
Thank you for stopping on my page and I hope that you not find it to not be just an entertaining idea but that you find that this website demonstrates some amazing skills that I’ve learned during my Software Development course at Grinnell College during Spring 2020. If not, let me personally tell you why I believe that this website demonstrates some of the skills I’ve developed with Ruby on Rails.
<br>
By working on this website, I have learned how to modify and create new pages with Ruby on Rails. Most importantly, I have learned how views, controllers, and models all fit together when designing a website. On this website you will see various pages, with the two most important being “Adoptees” and “Sign-Up”. With the “Sign-Up” page, I have learned how to integrate a form with a database and demonstrate the updated database on the “Adoptees” page. This website also demonstrates how I have learned how to develop a site with a “brand” as I keep the colors of each page consistent and therefore the site becomes something users can begin associating to the “Adopt a CS Major” brand. Finally, unseen to most eyes are all the failures and challenges I had to overcome to make this site functioning. By working through my problems, I have not only learned how to be a Ruby on Rails developer, but I have learned how to be a better software engineer in general.
Thank you for reading and I wish you health and happiness! :)

</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact <a href="https://www.linkedin.com/in/stefanieochoa/">Stefanie Ochoa </a> for questions, comments, and concerns!
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
 <b> For Adoptees:</b> <br>
  If you are looking to sign up as an "adoptee", go to our home page.
  You can navigate to the home page by clicking on the 'Home' button
  in the navigation bar. On the front page you will be able to click
  on the 'Sign Up!' button and fill out the form with the 
  appropriate information to complete your profile.
</p>  
<br>
<p>
  <b> For Adopters:</b> <br>
  Find our list of current adoptees by clicking on the 'Adoptees' button  in the navigation bar. There you will be able to see a list of 
  adoptees with their name and profile picture. Go through the adoptees
  and read their profiles. Once you find someone you're interesting in 
  "adopting" reach out to the individual by sending them an email!
</p>

<figure>
<center>
<%= link_to image_tag("study.jpg", alt: "CS Students", :size => "340x220"),
            'http://www.cs.grinnell.edu/drupal6/curriculum.html' %>
<figcaption>Image from Grinnell CS Website </figcaption>
</center>
</figure>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Welcome to <br> "Adopt A CS Major"</h1>

  <h2>
    This is site meant to help bring CS and non CS majors together by having people willingly volunteer to adopt a CS major.  <br/>
    <a href="https://www.freshu.io/tally-delong/5-things-computer-science-majors-are-tired-of-hearing" target="_blank">Learn about some CS major stereotypes!</a>
	<br>
	Here is a random name of a student you may adopt! : <i style ="color:blue;"><%= @result %> </i> <br>
	Don't like that student? Click <%= link_to 'New Name!', root_path%>
  </h2>
  <%= link_to "Sign Up!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<figure>
<center>
<%= link_to image_tag("kids.jpg", alt: "CS Students", :size => "340x220"),
            'http://www.cs.grinnell.edu/drupal6/curriculum.html' %>
<figcaption>Image from Grinnell CS Website </figcaption>
</center>
</figure>